package com.facegate.pipeline

import android.graphics.Bitmap
import android.graphics.PointF

/**
 * PIPELINE DATA MODELS
 * ====================
 * SHARED CONTRACT — every pipeline file imports from this.
 *
 * Rule: do not edit this file without a team sync. If your task needs
 * a new field, message the group
 */


// CONSTANTS

object PipelineConfig {

    // ── MobileFaceNet ──────────────────────────────────────
    const val MODEL_INPUT_SIZE   = 112          // px, fixed by MobileFaceNet
    const val EMBEDDING_SIZE     = 128          // fixed by MobileFaceNet
    const val MODEL_ASSET_PATH   = "models/mobilefacenet.onnx"

    // ── Camera ─────────────────────────────────────────────
    const val ANALYSIS_FPS       = 10
    const val FRAME_BUFFER_SIZE  = 8

    // ── Quality thresholds ─────────────────────────────────
    const val MIN_FACE_SIZE_RATIO     = 0.20f
    const val MAX_YAW_DEGREES         = 30f
    const val MAX_PITCH_DEGREES       = 20f
    const val MAX_ROLL_DEGREES        = 15f
    const val MIN_LANDMARK_CONFIDENCE = 0.7f
    const val MIN_LAPLACIAN_VARIANCE  = 80.0
    const val MIN_BRIGHTNESS          = 60f
    const val MAX_BRIGHTNESS          = 220f

    // ── Similarity thresholds ──────────────────────────────
    const val THRESHOLD_ACCEPT    = 0.60f
    const val THRESHOLD_REJECT    = 0.40f

    // ── Normalization ───────────────────────────────────────
    val MEAN = floatArrayOf(0.5f, 0.5f, 0.5f)
    val STD  = floatArrayOf(0.5f, 0.5f, 0.5f)
}


// STEP 1 — Face Detection Result

data class DetectedFace(
    val boundingBox: android.graphics.Rect,
    val yaw: Float,
    val pitch: Float,
    val roll: Float,
    val landmarks: List<PointF>,
    val landmarkConfidence: Float,
    val frameWidth: Int,
    val frameHeight: Int,
)

enum class FaceCountStatus {
    NO_FACE,
    SINGLE_FACE,
    MULTIPLE_FACES,
}


// STEP 2 — Quality Assessment Result

data class QualityResult(
    val passed: Boolean,
    val sharpness: Float,
    val brightness: Float,
    val faceSizeRatio: Float,
    val yaw: Float,
    val pitch: Float,
    val roll: Float,
    val landmarkConfidence: Float,
    val failReasons: List<QualityFailReason> = emptyList(),
    val qualityScore: Float = 0f,
)

enum class QualityFailReason {
    TOO_BLURRY,
    TOO_DARK,
    TOO_BRIGHT,
    FACE_TOO_SMALL,
    HEAD_TURNED_YAW,
    HEAD_TILTED_PITCH,
    HEAD_ROTATED_ROLL,
    LOW_LANDMARK_CONFIDENCE,
}


// STEP 3 — Aligned Face Crop

data class AlignedFace(
    val bitmap: Bitmap,
    val sourceFrame: Bitmap,
)


// STEP 4 — Embedding

data class FaceEmbedding(
    val vector: FloatArray,
    val inferenceTimeMs: Long,
) {
    init {
        require(vector.size == PipelineConfig.EMBEDDING_SIZE) {
            "Expected ${PipelineConfig.EMBEDDING_SIZE}-D embedding, got ${vector.size}"
        }
    }

    fun norm(): Float = Math.sqrt(vector.map { it * it }.sum().toDouble()).toFloat()
}


// STEP 5 — Similarity Match

data class SimilarityMatch(
    val topMatch: MatchCandidate?,
    val secondMatch: MatchCandidate?,
    val searchTimeMs: Long,
)

data class MatchCandidate(
    val studentId: String,
    val studentName: String,
    val cosineSimilarity: Float,
)


// STEP 6 — Attendance Decision

sealed class AttendanceDecision {

    data class Accept(
        val studentId: String,
        val studentName: String,
        val confidence: Float,
    ) : AttendanceDecision()

    data class Reject(
        val topSimilarity: Float,
        val reason: String,
    ) : AttendanceDecision()

    data class Ambiguous(
        val topCandidate: MatchCandidate?,
        val secondCandidate: MatchCandidate?,
        val reason: String,
    ) : AttendanceDecision()

    data class AlreadyMarked(
        val studentId: String,
        val markedAt: Long,
    ) : AttendanceDecision()
}


// FULL PIPELINE RESULT

data class PipelineResult(
    val decision: AttendanceDecision,
    val detectionMs: Long,
    val qualityMs: Long,
    val alignmentMs: Long,
    val inferenceMs: Long,
    val similarityMs: Long,
    val totalMs: Long,
)


// PIPELINE FRAME STATUS — what UI receives each frame

sealed class PipelineFrameStatus {
    object NoSession                                    : PipelineFrameStatus()
    object Processing                                   : PipelineFrameStatus()
    object NoFace                                       : PipelineFrameStatus()
    object MultipleFaces                                : PipelineFrameStatus()
    data class QualityFailed(val reasons: List<QualityFailReason>) : PipelineFrameStatus()
    data class Buffering(val framesCollected: Int, val framesNeeded: Int) : PipelineFrameStatus()
    data class Decision(val result: PipelineResult)     : PipelineFrameStatus()
}


// ENROLLMENT RESULT

sealed class EnrollmentResult {
    object Success                                          : EnrollmentResult()
    object NoFaceDetected                                   : EnrollmentResult()
    object MultipleFacesDetected                            : EnrollmentResult()
    data class QualityFailed(val reasons: List<QualityFailReason>) : EnrollmentResult()
    data class DuplicateRisk(
        val existingStudentId: String,
        val existingStudentName: String,
    ) : EnrollmentResult()
}
